# Generated by Django 4.1.3 on 2022-12-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bookID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tag', to='books.book'),
        ),
    ]
