# Generated by Django 4.1.3 on 2022-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
